---
name: Net-SNMP-Mixin
version: 0.06
author:
  - 'Karl Gaissmaier <karl.gaissmaier (at) uni-ulm.de>'
abstract: mixin framework for Net::SNMP
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Net::SNMP: 0
  Package::Generator: 0.102
  Package::Reaper: 0.102
  Scalar::Util: 1.18
  Sub::Exporter: 0.978
  perl: 5.6.0
build_requires:
  Module::Build: 0
provides:
  Net::SNMP::Mixin:
    file: lib/Net/SNMP/Mixin.pm
    version: 0.06
  Net::SNMP::Mixin::System:
    file: lib/Net/SNMP/Mixin/System.pm
    version: 0.06
  Net::SNMP::Mixin::Util:
    file: lib/Net/SNMP/Mixin/Util.pm
    version: 0.06
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
